---
title: "Blog post 6 and 7"
author: "Team 12 "
date: "2023-12-04"
date-modified: "2023-12-04"
draft: FALSE
---

### Introduction of Datasets/Main Question:
Our team’s project originally investigated whether there is correlation between civilian complaints and police departments employing lethal force methods. Specifically, we decided to investigate if this was true: U.S. police departments that employ less-lethal force methods receive fewer civilian complaints compared to those that use more lethal methods. We decided to also analyze how the diversity of police departments across different states in the U.S. correlates with civilian complaints, which became another independent variable of ours (diversity and less lethal force methods). As we delved into our data through visualizations and analyses, we discovered that the relationship between civilian complaints and less-lethal force methods was not as clear-cut as anticipated. Instead, our preliminary findings indicated a more significant correlation between population size and less-lethal force methods. This insight led us to refine our research direction. To enrich our exploratory data analysis process, we will incorporate an additional variable: the diversity of police departments across different U.S. states. Thus, we decided to investigate a newer tentative thesis: More diverse police departments receive fewer civilian complaints. We pulled 2 datasets from a Fact checking sheet, Use of Force dataset and Civilian Complaints dataset. The civilian complaints dataset is a comprehensive dataset of complaints against police departments across various cities in the US, such as civilian complaints, use of force complaints, discrimination complaints, and criminal complaints. We used this dataset to analyze trends in police complaints, and assess the effectiveness of complaint resolution processes. We then analyzed the Use of Force dataset, which provides detailed information about the use of force by various police departments across the United States, including police department and state, ORI (unique identifier for each police department), and population size served by the police department. It includes data from multiple years and covers different forms of force by various police departments across the US.

### Data Visualization
In line with our revised research question, we have enriched our data analysis approach by creating new visualizations. These include bar charts, heatmaps, and linear regression graphs, designed to present a more comprehensive picture of the relationship between the racial composition of police forces and the distribution of civilian complaints. Our focus has shifted from merely examining the correlation between complaints and less-lethal force to a broader consideration of police force diversity. Our first bar chart aggregates civilian complaints reported from 2016 to 2022 for each police department. These totals are then plotted against the Shannon Diversity Index, calculated based on the racial and ethnic composition of the officers. This index serves as a quantitative measure of diversity, with higher values indicating greater diversity. We grouped the data into ten categories representing different ranges of diversity. The second bar chart delves into complaints per capita, providing a nuanced view by accounting for the population size served by each police department. This helps us assess whether a higher diversity within police departments correlates with variations in the rate of complaints.We created a heatmap as a correlation matrix to evaluate the relationship between the diversity in police departments and the total civilian complaints reported in 2020. This visualization allows us to observe potential correlations and patterns more intuitively.


### EDA countinuing analysis 
Our visualizations revealed a positive correlation between police force diversity and civilian complaints, a finding that initially seems counterintuitive to our hypothesis. This insight propels us to investigate further: we are now exploring potential confounders or other underlying factors that may influence this relationship. Our goal is to understand the complexities and nuances of this correlation, ensuring that our analysis accounts for various influencing factors.
By refining our visualizations and delving deeper into the data, we aim to provide a well-rounded and thorough analysis of the impact of police force diversity on civilian complaints, contributing to the ongoing discourse on policing practices and community relations.


